buyer: bigValiant
agent: 代理者
spring:
  mail:
    host: smtp.qq.com
    username: ray_am@foxmail.com
    password: opgrjgvmfiymjgae
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: spring-boot-demo
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
      username: root
      password: 1233456
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
      username: root
      password: 1233456
    slave2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
      username: root
      password: 1233456
  application:
    name: prometheus-test #应用名称

logging:
  level: debug
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoint:
    health:
      show-details: always  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}