buyer: bigValiant
agent: 代理者
spring:
  mail:
    host: smtp.qq.com
    username: ray_am@foxmail.com
    password: opgrjgvmfiymjgae
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: spring-boot-demo
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
      username: root
      password: 1233456
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
      username: root
      password: 1233456

logging:
  level:
    com.
