buyer: bigValiant
agent: 代理者
spring:
  mail:
    host: smtp.qq.com
    username: ray_am@foxmail.com
    password: opgrjgvmfiymjgae
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: spring-boot-demo